name: first-workflow
on: 
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: ubuntu-latest
   steps:
     - name: print welcome message
       run: echo 'welcome'
     - name: checkout-repository
       uses: actions/checkout@v6.0.2
     - name: show-files
       run: ls -la

    
